"""Add users table and update contacts with user relationship

Revision ID: 3079e77d4c14
Revises: e8c4a9fd3b27
Create Date: 2025-05-03 23:52:25.232505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3079e77d4c14'
down_revision: Union[str, None] = 'e8c4a9fd3b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create users table
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # Create a default admin user for existing contacts
    from sqlalchemy.sql import table, column
    from sqlalchemy import String, Integer, Boolean, DateTime
    from passlib.context import CryptContext
    import datetime
    
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    
    users = table('users',
        column('id', Integer),
        column('username', String),
        column('email', String),
        column('hashed_password', String),
        column('is_active', Boolean),
        column('is_verified', Boolean),
        column('created_at', DateTime),
        column('updated_at', DateTime)
    )
    
    # Insert a default user with a secure password
    op.bulk_insert(users,
        [
            {
                'id': 1,
                'username': 'admin',
                'email': 'admin@example.com',
                'hashed_password': pwd_context.hash('adminpassword'),
                'is_active': True,
                'is_verified': True,
                'created_at': datetime.datetime.utcnow(),
                'updated_at': datetime.datetime.utcnow()
            }
        ]
    )
    
    # Add user_id column as nullable first
    op.add_column('contacts', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Set all existing contacts to belong to the default admin user
    op.execute("UPDATE contacts SET user_id = 1")
    
    # Now make user_id non-nullable
    op.alter_column('contacts', 'user_id', nullable=False)
    
    # Fix email index (no longer unique)
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    
    # Create foreign key constraint
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=False)
    op.drop_column('contacts', 'user_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
